image: node:10.5.0 # can be upgraded, depending on your node version used

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
